### ISSUE TITLE
tags not currently handled

### ISSUE THREAD

**Issue by AntoineSoetewey** [coolbutuseless/svgparser#1]
Hello,

Following your [article](https://coolbutuseless.github.io/2021/12/02/introducing-svgparser-an-svg-renderer-in-plain-r/?fbclid=IwAR2N7I1UJaEWU2E92e2vZwPViBp_8QgBBY-oxxy-COIR8iQTRs0rhVO80JU), I tried to include this [svg file](https://statsandr.com/blog/files/overview-statistical-tests-statsandr.svg) in a R Markdown document with the following code:

```{r}
grob <- svgparser::read_svg("overview-statistical-tests-statsandr.svg")
grid::grid.draw(grob)
```

I encounter a warning (but the HTML file is generated):

```
SVG contains a tag not currently handled: <switch>
SVG contains a tag not currently handled: <a>
SVG contains a tag not currently handled: <image>
```

And the text is not appearing on the output HTML file:

![Screenshot 2021-12-02 at 14 35 41](https://user-images.githubusercontent.com/17910063/144432399-6850876a-61a6-4464-9f83-444e3db85d41.png)

Any idea how I could fix this?

Thanks in advance for your help.

Regards,
Antoine

**Comment by coolbutuseless** [comment]
Thanks for detailed bug report and inclusion of a link to the SVG file - this is very helpful.

Notes:
* 'a' tag - can probably render text contents, but definitely won't be a clickable link (as there's no such thing in R grid graphics objects)
* 'image' tag -  Inclusion as a rasterGrob() seems likely. will investigate
    * this SVG contains images defined inline as base64 encoded PNG objects.
    * i.e. this is *not* a URL link to an external file.
    * svgparser should support both external files and base64 encoded inclusions.
* 'switch' tag - I need to investigate this one.
    * this <switch> is used to decide whether to display HTML text object (as a 'foreignObject' or as an SVG <text> object.
    * I'm not planning on adding 'foreignObject' support at the moment.
    * I'm not planning on adding HTML support at the moment.
    * What I can do is implement the <switch> statement to return the first non-NULL renderable child-object as an initial fix.  The actual code for deciding which of the objects to render seems to be pretty complex.
    * E.g. This switch statement in this SVG relies on the [requiredFeatures](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/requiredFeatures) parameter - which is a deprecated SVG feature.

**Comment by coolbutuseless** [comment]
Experiment in progress

* 'a' tags are just 'g' (group) tags which are clickable in SVG, but we'll lose the clickability since {grid} doesn't have hyperlinked grobs
* 'image' tag  basic support done.  
    * I feel there are still problems with sizing. 
    * Need to assemble a few more test cases.
    * In your example the "image" is the twitter logo in the bottom left
* 'switch' tag naive version done.
    * switch chooses between child elements and renders one of them
    * the rules for rendering can get quite complex.
    * Your SVG uses a deprecated choice mechanism.
    * svgparser (for now) just shows the first render-able child element.
    * The issue with your SVG is that the text is HTML text wrapped in a 'foreignObject' tag (which svgparser will likely never support), and the fallback text chosen by the switch statement is svg text which is actually truncated in the original SVG for some reason.

So all up - this is about as good as your example is going to look.  Can probably do some fiddling with the font-sizing with the `font_scale` argument, but it's always going to be truncated (unless you hack on the SVG file)

![Screen Shot 2021-12-03 at 8 57 37 pm](https://user-images.githubusercontent.com/181818/144592393-8e1a8876-f2f4-4f4a-97ee-13ccbce8ac30.png)

**Comment by AntoineSoetewey** [comment]
Thanks for that!

**Comment by coolbutuseless** [comment]
Updates to image rendering (for correct positioning) and setting `font_scale = 0.66` gets as close as this is going to come for {svgparser}.

New v0.1.1 being released soon.
![Screen Shot 2021-12-05 at 7 51 36 am](https://user-images.githubusercontent.com/181818/144725740-a1ba084d-d6cf-41c9-9769-e4a360c91a0b.png)

**Comment by AntoineSoetewey** [comment]
Many thanks!
